apiVersion: apps/v1
kind: Deployment
metadata:
  name: whalesay
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    spec:
      containers:
      - name: whalesay
        image: docker/whalesay:latest
        ports:
        - containerPort: 80
	CMD: ["hello"]
