apiVersion: apps/v1
kind: Deployment
metadata:
  name: whalesay-deployment
spec:
  selector:
    matchLabels:
      app: whalesay
  replicas: 3 
  template:
    metadata:
      labels:
        app: whalesay
    spec:
      containers:
      - name: whalesay
        image: docker/whalesay:lates
        ports:
        - containerPort: 80
        command: ["/bin/sh","-c"]
        args: ["cowsay hello; sleep infinity"]
